### ISSUE TITLE
Provide quality limitation reason in output video stats

### ISSUE THREAD

**Issue by jackshen** [DolbyIO/web-webrtc-stats#2]
Provide `qualityLimitationReason` in `OutputVideo`.

Linked to this issue in Dolby Millicast RTS app: https://github.com/dolbyio-samples/rts-app-react-publisher-viewer/issues/325

**Comment by FabienLavocat** [comment]
Available in version 0.2.0

![image](https://user-images.githubusercontent.com/4154532/227396001-edebcde0-4264-4108-89b5-8a23de2c60ac.png)
